OmniAuth.config.logger = Rails.logger

Rails.application.config.middleware.use OmniAuth::Builder do
  provider :google, ENV['YAMMERGRATION_GOOGLE_CLIENT_ID'], ENV['YAMMERGRATION_GOOGLE_CLIENT_SECRET']
  provider :twitter, ENV['YAMMERGRATION_TWITTER_CLIENT_ID'], ENV['YAMMERGRATION_TWITTER_CLIENT_SECRET']
  provider :facebook, ENV['YAMMERGRATION_FACEBOOK_CLIENT_ID'], ENV['YAMMERGRATION_FACEBOOK_CLIENT_SECRET']
  provider :yammer, ENV['YAMMERGRATION_YAMMER_PRODUCTION_CLIENT_ID'], ENV['YAMMERGRATION_YAMMER_PRODUCTION_CLIENT_SECRET']
  provider :yammer_staging, ENV['YAMMERGRATION_YAMMER_STAGING_CLIENT_ID'], ENV['YAMMERGRATION_YAMMER_STAGING_CLIENT_SECRET']
end